frequency: 50

odom_frame: odom
base_link_frame: base_link

two_d_mode: true

world_frame: odom

odom0: /odom
odom0_config: [true, true, false,
               false, false, true,
               true, true, false,
               false, false, false,
               false, false, false]


